import { isTrustedMutationOrigin } from "./core-identity-policy.js";
import { CreatorApplicationPolicyError } from "./creator-application-policy.js";

type ApplicantService = { getForApplicant(input: { userId: string }): Promise<unknown>; saveDraft(input: Record<string, unknown>): Promise<unknown>; submit(input: Record<string, unknown>): Promise<unknown>; withdraw(input: Record<string, unknown>): Promise<unknown> };
type CreatorApplicationHttpHandlers = { get(request: Request): Promise<Response>; save(request: Request): Promise<Response>; submit(request: Request): Promise<Response>; withdraw(request: Request): Promise<Response> };
function json(status: number, payload: Record<string, unknown>) { return Response.json(payload, { status, headers: { "cache-control": "no-store", "referrer-policy": "no-referrer" } }); }
async function body(request: Request): Promise<Record<string, unknown> | null> { if (!request.headers.get("content-type")?.toLowerCase().startsWith("application/json")) return null; try { const value=await request.json(); return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string,unknown> : null; } catch { return null; } }
function expectedVersion(request: Request): number | null { const raw=request.headers.get("if-match"); if(!raw || !/^[1-9]\d*$/u.test(raw)) return null; const value=Number(raw); return Number.isSafeInteger(value) ? value : null; }
function serviceFailure(error: unknown): Response { return error instanceof CreatorApplicationPolicyError ? json(422,{code:"POLICY_REJECTED"}) : json(503,{code:"CREATOR_APPLICATION_UNAVAILABLE"}); }
export function createCreatorApplicationHttpHandlers(input: { trustedOrigins: readonly string[]; authenticate(headers: Headers): Promise<{userId:string}|null>; service: ApplicantService }): CreatorApplicationHttpHandlers {
  async function applicant(request: Request): Promise<{userId:string}|Response> { try { return await input.authenticate(request.headers) ?? json(401,{code:"AUTHENTICATION_REQUIRED"}); } catch { return json(503,{code:"CREATOR_APPLICATION_UNAVAILABLE"}); } }
  async function mutate(request: Request, operation: "save"|"submit"|"withdraw") { if(request.method!=="POST") return json(405,{code:"METHOD_NOT_ALLOWED"}); if(!isTrustedMutationOrigin({origin:request.headers.get("origin"),trustedOrigins:input.trustedOrigins})) return json(403,{code:"UNTRUSTED_ORIGIN"}); const actor=await applicant(request); if(actor instanceof Response) return actor; const idempotencyKey=request.headers.get("idempotency-key"); if(!idempotencyKey) return json(400,{code:"INVALID_REQUEST"}); const version=expectedVersion(request); if(operation !== "save" && version===null) return json(400,{code:"INVALID_REQUEST"}); const payload=operation === "withdraw" ? {} : await body(request); if(payload===null) return json(400,{code:"INVALID_REQUEST"}); try { const command={...payload,userId:actor.userId,idempotencyKey,...(version===null?{}:{expectedVersion:version})}; const application=operation === "save" ? await input.service.saveDraft(command) : operation === "submit" ? await input.service.submit(command) : await input.service.withdraw(command); return json(200,{application}); } catch(error) { return serviceFailure(error); } }
  return { async get(request: Request) { if(request.method!=="GET") return json(405,{code:"METHOD_NOT_ALLOWED"}); const actor=await applicant(request); if(actor instanceof Response) return actor; try { return json(200,{application:await input.service.getForApplicant({userId:actor.userId})}); } catch(error) { return serviceFailure(error); } }, save: (request: Request) => mutate(request,"save"), submit: (request: Request) => mutate(request,"submit"), withdraw: (request: Request) => mutate(request,"withdraw") };
}
