import { defineConfig } from "@playwright/test";

export default defineConfig({
  testDir: "./tests",
  testMatch: "**/*.playwright.ts",
  testIgnore: [
    "increment-three-disabled.playwright.ts",
    "creator-page-management.playwright.ts",
    "public-creator-discovery.playwright.ts",
    "public-content-reporting.playwright.ts",
  ],
  timeout: 30_000,
  workers: 1,
  use: {
    baseURL: "http://127.0.0.1:4173",
    browserName: "chromium",
    timezoneId: "UTC",
    ...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH
      ? { launchOptions: { executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH } }
      : {}),
  },
  webServer: {
    command:
      "node node_modules/next/dist/bin/next dev --webpack --hostname 127.0.0.1 --port 4173",
    url: "http://127.0.0.1:4173/creator/apply",
    env: {
      NODE_ENV: "test",
      APP_ENV: "test",
      APP_REVISION: "playwright",
      CREATOR_PUBLISHING_MODE: "disabled",
      DATABASE_URL: "postgresql://pawket:playwright@127.0.0.1:5432/pawket_playwright",
      VALKEY_URL: "redis://127.0.0.1:6379",
      METRICS_TOKEN: "playwright-metrics-token-000000000000",
      APP_BASE_URL: "http://127.0.0.1:4173",
      AUTH_TRUSTED_ORIGINS: "http://127.0.0.1:4173",
      BETTER_AUTH_SECRETS: "1:playwright-only-better-auth-secret-000000000000",
      PII_ACTIVE_KEY_ID: "playwright-pii-v1",
      PII_KEYRING_JSON: '{"playwright-pii-v1":"AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE="}',
      PII_LOOKUP_HMAC_KEY: "AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgI=",
      SECURITY_EMAIL_ADAPTER: "disabled",
      VERIFICATION_DEPOSIT_AMOUNT_VND: "1000",
      OPERATING_BANK_BIN: "000000",
      OPERATING_BANK_ACCOUNT_NUMBER: "000000",
      OPERATING_BANK_ACCOUNT_NAME: "PAWKET PLAYWRIGHT",
      VN_BUSINESS_CALENDAR_VERSION: "vn-playwright-v1",
      VN_BUSINESS_HOLIDAYS: "[]",
      AUTH_USER_ABSOLUTE_TTL_SECONDS: "2592000",
      AUTH_USER_IDLE_TTL_SECONDS: "604800",
      AUTH_OWNER_ABSOLUTE_TTL_SECONDS: "43200",
      AUTH_OWNER_IDLE_TTL_SECONDS: "1800",
      AUTH_MFA_PENDING_TTL_SECONDS: "600",
      AUTH_PRIMARY_STEP_UP_TTL_SECONDS: "900",
      AUTH_OWNER_TOTP_STEP_UP_TTL_SECONDS: "300",
      AUTH_TOTP_MAX_FAILED_ATTEMPTS: "5",
      AUTH_TOTP_LOCKOUT_SECONDS: "900",
      AUTH_PASSWORD_RESET_TTL_SECONDS: "1800",
    },
    reuseExistingServer: false,
    timeout: 120_000,
  },
});
